mutation DeleteTodo($id: String!) {
  deleteTodo(id: $id)
}

mutation UpdateTodo($input: TodoUpdateInput!) {
  updateTodo(input: $input) {
    id
    description
    completed
  }
}

mutation UpdateTodos($input: TodoUpdateManyInput!) {
  updateTodos(input: $input)
}
