scalar Void

type Todo {
  id: String!
  description: String!
  completed: Boolean!
}

input TodoCreateInput {
  description: String!
  completed: Boolean
}

input TodoUpdateInput {
  id: String!
  description: String
  completed: Boolean
}

type Query {
  todo(id: String!): Todo
  todos: [Todo!]!
}

type Mutation {
  createTodo(input: TodoCreateInput!): Todo!
  updateTodo(input: TodoUpdateInput!): Todo!
  deleteTodo(id: String!): Void
  deleteTodos(completed: Boolean): Void
}

schema {
  query: Query
  mutation: Mutation
}
